### ISSUE TITLE
[18] #2643 Basic HTLC support

### ISSUE THREAD

**Issue by sschiessl-bcp** [blockchainprojects/bitshares-ui#104]
https://github.com/bitshares/bitshares-ui/issues/2643

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp please look PR #105 . The task is not done but I want to be sure that I am on the right way. Also can you help me with HtlcActions redeem method? What data it should get for preimage? There is an error (missing preimage size)   If it gets an array.

**Comment by sschiessl-bcp** [comment]
Please have a look at 
https://github.com/bitshares/bitsharesjs/tree/develop/examples

and check if HtlcActions does it analogously. Checking the PR now
