### ISSUE TITLE
[3.3] #2742 Further voting restyle and refactor

### ISSUE THREAD

**Issue by sschiessl-bcp** [blockchainprojects/bitshares-ui#116]
https://github.com/bitshares/bitshares-ui/issues/2742

**Comment by sschiessl-bcp** [comment]
First task for you @Metizik is only to extract the components and add the router
https://github.com/blockchainprojects/bitshares-ui/pull/114#issuecomment-498234939

**Comment by mettizik** [comment]
I extracted all tabs into separate almost stateless components from AccountVoting component and will finish moving to new style-guide on Tuesday (Monday is a holiday in Ukraine)
