### ISSUE TITLE
[3.35] [3.1.190618-rc1] Refine release candidate

### ISSUE THREAD

**Issue by sschiessl-bcp** [blockchainprojects/bitshares-ui#122]
Some smaller tasks

 - [x] [0.25] https://github.com/bitshares/bitshares-ui/issues/2780
 - [x] [0.5] https://github.com/bitshares/bitshares-ui/issues/2778
 - [x] [0.25] https://github.com/bitshares/bitshares-ui/issues/2777
 - [x] [0.1] https://github.com/bitshares/bitshares-ui/issues/2775
 - [x] [0.75] https://github.com/bitshares/bitshares-ui/issues/2776
 - [x] [1] https://github.com/bitshares/bitshares-ui/issues/2762

@Metizik @VerevkinAlexander this would be considered priority to get the release candidate done.

**Comment by sschiessl-bcp** [comment]
Also [0.5] https://github.com/bitshares/bitshares-ui/issues/2786

**Comment by VerevkinAlexander** [comment]
> Also [bitshares#2786](https://github.com/bitshares/bitshares-ui/issues/2786)

done
