### ISSUE TITLE
[6.5] #2755 Show info about pending force-settlement orders in account info

### ISSUE THREAD

**Issue by sschiessl-bcp** [blockchainprojects/bitshares-ui#123]
https://github.com/bitshares/bitshares-ui/issues/2755

Add a new table below the open orders showing the settle orders.

**Comment by VerevkinAlexander** [comment]
Can you give me some account with created settle orders? Or tell me how to create it on the testnet because now I have the error . 
![image](https://user-images.githubusercontent.com/43240282/59874471-ef4a7800-93a6-11e9-9524-891d0501051c.png)

**Comment by sschiessl-bcp** [comment]
Try it on mainnet with bitUSD or bitCNY. I can either send you some, or you buy it and put it on the invoice.

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp should we do come thing with it or it can be closed?
