### ISSUE TITLE
[1] Unable to input 0.0000001 as price when placing new order

### ISSUE THREAD

**Issue by sschiessl-bcp** [blockchainprojects/bitshares-ui#16]
See description in original issue #1915

**Comment by VerevkinAlexander** [comment]
I investigated the reason of issue and found that we use general js integer, that is not suitable for operations with currency. I decided to use BigNumber.js.

**Comment by sschiessl-bcp** [comment]
Ok cool, keep me updated what you find out

**Comment by sschiessl-bcp** [comment]
Resovled with  #1961
