### ISSUE TITLE
[14.5] Refine wallet merchant protocol #2960

### ISSUE THREAD

**Issue by sschiessl-bcp** [blockchainprojects/bitshares-ui#169]
https://github.com/bitshares/bitshares-ui/issues/2960

**Comment by VerevkinAlexander** [comment]
Please confirm is I am on the correctly understand your concept. 
![image](https://user-images.githubusercontent.com/43240282/62083040-bb445b80-b25e-11e9-9303-6e211cc76870.png)

**Comment by sschiessl-bcp** [comment]
Yes! Please give the barcode a title (same font as the invoice) and put the toggle under it. I think it would be better UX if the toggle is a secondary button that changes its text instead of the checkbox.

**Comment by VerevkinAlexander** [comment]
![image](https://user-images.githubusercontent.com/43240282/62172775-257efe00-b33c-11e9-9266-2075a29a00a1.png)
