### ISSUE TITLE
[37.5] Simplified order form for ordinary users (i.e. non-traders) #2973

### ISSUE THREAD

**Issue by sschiessl-bcp** [blockchainprojects/bitshares-ui#175]
See my comment here https://github.com/bitshares/bitshares-ui/issues/2973#issuecomment-518201813 and below

**Comment by Metizik** [comment]
@sschiessl-bcp , can you please clarify where can Icon and Name be received from for Sell & Receive assets selectors? And the "name" field is a search box, similar to "MarketPicker" component?

**Comment by sschiessl-bcp** [comment]
The favorites render the icons
![image](https://user-images.githubusercontent.com/33128181/62684706-8bfdbf00-b9c1-11e9-91db-c358f08d388c.png)

Use "symbol" for the name, the existing AssetSelector should do the trick
![image](https://user-images.githubusercontent.com/33128181/62684813-c5362f00-b9c1-11e9-87e0-3a5060fadc04.png)

Essentially it is a new AmountSelector component similar to the existing one but a bit restyled

**Comment by Metizik** [comment]
@sschiessl-bcp , few questions regarding further implementation:
1. What is the value of "your price" in the "Price" table? Is it the best market price or arithmetic mean of all orders that would get matched?
2. I suggest that, if the user enters an amount to sell, amount to receive is filled automatically, and vice versa, right? How it should be calculated?

**Comment by sschiessl-bcp** [comment]
1. This is the price calculated form the amounts that you see in the too inputs above.

2. Exactly. If you enter the amount in the "Sell" and user has selected asset "Receive", you check the current open orders in the respective market and virtually match all open orders until you have sold everything (always with the best price if multiple orders), then you know how much of the "Receive" asset you can get. If you edit "Receive" then you do the same "just" inverse.

**Comment by Metizik** [comment]
@sschiessl-bcp, working on issues listed in #186 PR:

- [x] Implement assets switch on same asset selected - 30m
- [x] Transactions calculation functions - 2h
- [x] Numbers refactoring over the components - 1h
- [x] Add liquidity penalty to getTotalFeePercent calculation - 20m
- [x] Add unknown asset icon - 15m
- [x] Add base/quote price to orders and prices - 30m
- [ ] Research issue reported and fix it - ?? ~2h 
- [x] Add cumulative sums and group by switch - 3h

Please let me know if those estimates make sense to you, or maybe there are some hints to reduce research effort required

**Comment by Metizik** [comment]
@sschiessl-bcp 
1. All of the above tasks are completed.
Except for the bug you described in point 5 of the comment https://github.com/blockchainprojects/bitshares-ui/pull/186#issuecomment-524522925
It's not producing for me.
Orders are now matched according to the approach you described i.e. the user gets the best price.

2. By the way, as far as I understand, in such a volatile market as BTS/CNY it is possible that the user's order will not be successfully closed in the near future after the creation of the price, if the price starts to fall.
If so, what are the reasonable steps you see to resolve this issue?
Perhaps, when creating an order it is necessary to take the price for the order with a margin for market volatility.
And the user should receive a warning in the UI that the indicated price may differ from the actual price.

3. Please clarify for me the principle of how the selection of assets in the Receive selector should be carried out?
Now it initially has the same list as the Sell selector. And then the user can enter three characters to find any of the existing assets.
But there are markets where there are no open orders. So the price can't be calculated for them.

4. I am currently working on the following component improvements:
  - make the Sell button disabled if there are insufficient funds on the balance sheet - 1.5h
  - set as initially selected assets if the Quick trade component is opened by a tooltip button above a currency pair - 1.5h
  - there is a bug when Quick trade is opened without a logged in user, and then the user logs in, the Asset Selector is disabled - 1.5h
