### ISSUE TITLE
[0.75] Unable to view the 5th page of account activities #3036

### ISSUE THREAD

**Issue by sschiessl-bcp** [blockchainprojects/bitshares-ui#181]
https://github.com/bitshares/bitshares-ui/issues/3036

Please investigate and confirm this problem, and if reproducable, fix it :)

**Comment by Metizik** [comment]
@sschiessl-bcp , Will do first priority tomorrow morning

**Comment by sschiessl-bcp** [comment]
https://github.com/bitshares/bitshares-ui/pull/3075#issue-321720634
