### ISSUE TITLE
[3.5] Adapt error messages to new JSON-RPC of bitshares-core 3.2.0 #3040

### ISSUE THREAD

**Issue by sschiessl-bcp** [blockchainprojects/bitshares-ui#185]
https://github.com/bitshares/bitshares-ui/issues/3040

**Comment by Metizik** [comment]
@sschiessl-bcp , regarding this issue there are few questions to clarify:
1. The error handling logic is now hidden in `TransactionBuilder` of bitsharesjs. So to implement requested adoption I need to modify bitsharesjs codebase, or there is another preferred way here?
2. After changes applied - do we need to maintain older JSON-RPC version compatibility? If so, is there any nodes with older JSON-RPC I can test compatibility against?
