### ISSUE TITLE
[6][Showcases] General frame

### ISSUE THREAD

**Issue by sschiessl-bcp** [blockchainprojects/bitshares-ui#33]
Original issue #1857

Branch already created (1857_Showcases_Frame) and header item added (https://github.com/bitshares/bitshares-ui/issues/1857#issuecomment-432995231)

Task:
- [x] Create a component that contains one single tile that has as props:
  - target (function handle or path to navigate to
  - title
  - description
  - icon
- [x] Create a component for the new header item that displays a list of tiles in a grid, please suggest a style, the screenshot has only a simple rectangle

![image](https://user-images.githubusercontent.com/33128181/47497527-a879a200-d85a-11e8-8781-77d2dde8d3bf.png)

I imagine that the Showcase component has a list that is uses to dynamically populate all the tiles, e.g. 
```
const tiles = [
   {
       title: "Some title",
       target: () => {},
       description: "Some longer but not too long text",
       icon: "some-icon"  // see Icons app/compoentns/Icon/Icon
   },
   {
       title: "Off the book trade",
       target: () => {},
       description: "Trade directly with another user (swap assets)",
       icon: "swap"
   },
   // .... even more tiles in this list
]
```

**Comment by VerevkinAlexander** [comment]
I created those components. Have you suggestions about style?

**Comment by sschiessl-bcp** [comment]
Open to suggestions, maybe round corners. Keep it simple for now, styling can be done afterwards as well.

**Comment by sschiessl-bcp** [comment]
Any update here?

**Comment by VerevkinAlexander** [comment]
> Any update here?

No. Should I take other tasks from the original issue?

**Comment by sschiessl-bcp** [comment]
I thought you will create a new style. But if you won't that is fine. Please create PR
