### ISSUE TITLE
committee-account activities page white screen

### ISSUE THREAD

**Issue by sschiessl-bcp** [blockchainprojects/bitshares-ui#40]
Original issue #1999

Please investigate and report where the error comes from.

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp 
This issue is reproduced with 100% rate in the case when we open several browser tabs with any page. Its occurs during fetching in gatewayMethods.js .  It`s not reproduced with FireFox and looks like a Chrome feature https://www.chromestatus.com/feature/5527160148197376

**Comment by VerevkinAlexander** [comment]
The reason of white screen was missing notification component in bitshares-ui-style-guide. After deleting node modules and reinstalling the package problem gone

**Comment by sschiessl-bcp** [comment]
Was there any code change necessary now?

Or is the multiple tab reason above the only reason? Does it still reproduce after reinstalling with multiple tabs?

**Comment by VerevkinAlexander** [comment]
> Was there any code change necessary now?
> 
> Or is the multiple tab reason above the only reason? Does it still reproduce after reinstalling with multiple tabs?

oh sorry, This comment is not for this issue

**Comment by sschiessl-bcp** [comment]
Can you check this comment please
https://github.com/bitshares/bitshares-ui/issues/1999#issuecomment-445359238
