### ISSUE TITLE
After site crash user sees just white screen.

### ISSUE THREAD

**Issue by driverdevteam** [blockchainprojects/bitshares-ui#5]
1. Open the site with pop-up "Create new user" and "Login"
2. Disconnect the internet.
3. Click on the button "Create account" (the site will propose you to fill the fields "Account Name" and 
   "Confirm password") The fields are filled automatically with the previous Account name and password.
4. Wait 10-15 seconds, while "Connection out of sync" pop-up appears.
5. Click on the  button "Cancel" in the pop-up "Connection out of sync" (the pop-up will close)
6. Click on the button "Create account" - nothing happened
7. Click on the button "Login" - the pop-up for Login will opens
8. Close the opened pop-up by the clicking on the cross in the top right corner.
9. Scroll up and down the screen.

 	The message will appear in the center of the screen with the sentence "Connecting to API server: [name of the server] and preloader.
 	Next message will appear on the top left corner with the sentence: 
"Unable to connect API node 
wss://api.bts.mobi/ws, falling back to know working nodes. 
Error was: [object event]"

**AR:** After site crash user sees just white screen.
**ER:** After crash user sees the page with 500 error status of the crash.

**Comment by sschiessl-bcp** [comment]
Does this still reproduce?
