### ISSUE TITLE
[11] ANTify tooltips

### ISSUE THREAD

**Issue by sschiessl-bcp** [blockchainprojects/bitshares-ui#53]
Original issue https://github.com/bitshares/bitshares-ui/issues/2137

Please see the issue for the task list, report back in here with your suggested solution.

Estimate 2 for creating one replacement for review (see original issue)

**Comment by VerevkinAlexander** [comment]
There are 105 tooltips in the project. 
As they are placed in different components and Ant Tooltip should be a wrapper for components I do not see the way ho to replace them by a script.
 For tooltips, without actions inside it, we can use ToolTip, if we need to add some link to the tooltip or add action we can use Popover
PR #54 added for review

**Comment by sschiessl-bcp** [comment]
Please do a couple more (maybe 5 more) so I can get a better idea of the integration, looking good so far.

**Comment by VerevkinAlexander** [comment]
Added more tooltips

**Comment by sschiessl-bcp** [comment]
Please continue with this issue. Let me know when you encounter any unusual rendering or usages or tooltips

**Comment by VerevkinAlexander** [comment]
ok

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp  I found that Ant Tooltip does not support the HTML-like text format 
https://github.com/blockchainprojects/bitshares-ui/blob/develop/app/components/Account/CreateAccountPassword.jsx#L271
https://github.com/blockchainprojects/bitshares-ui/blob/develop/app/components/Modal/BorrowModal.jsx#L1056
https://github.com/blockchainprojects/bitshares-ui/blob/develop/app/components/Utility/AssetName.jsx#L106
https://github.com/blockchainprojects/bitshares-ui/blob/develop/app/components/Utility/TotalBalanceValue.jsx#L289

**Comment by VerevkinAlexander** [comment]
> @sschiessl-bcp I found that Ant Tooltip does not support the HTML-like text format
> https://github.com/blockchainprojects/bitshares-ui/blob/develop/app/components/Account/CreateAccountPassword.jsx#L271

I have found the solution for this 
` <Tooltip overlay={<div dangerouslySetInnerHTML={{ __html: counterpart.translate("tooltip.generate") }}></div>}>`

But in this way, we will include XSS vulnerability

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp is it possible to use dangerouslySetInnerHTML ?

**Comment by sschiessl-bcp** [comment]
Best not to, but acceptable for the transition. How many cases have you found?

**Comment by VerevkinAlexander** [comment]
> Best not to, but acceptable for the transition. How many cases have you found?

4
