### ISSUE TITLE
[27][Showcases] Escrowed transfer, or off-the-book trade

### ISSUE THREAD

**Issue by sschiessl-bcp** [blockchainprojects/bitshares-ui#56]
Original Issue https://github.com/bitshares/bitshares-ui/issues/1859

I have created a mockup on paper, I hope you can follow what I tried to visualize
![image](https://user-images.githubusercontent.com/33128181/49009142-0c4ffd00-f170-11e8-900c-2f24ab8d49ae.png)

Please create a component for that, that also hooks into the header (dynamic item) with its own route. In the picture there are sub-components A, B and C (in blue circes). For screens bigger than smallScreen, keep the arrangement as is. For screens smaller or equal, do a one column view and arrange A, B and C vertically.

In the components, there are Account selectors A and B, and Asset selectors (within the selector C is the amount and X the asset on the left side, and D/Y respectively on the right side). The third component merely displays in understandable language what happens, and shows the price (should also be changeable to allow for proper UX).

Under the components should be a "Propose" button in a separate line.

**Comment by VerevkinAlexander** [comment]
I created  new component EscrowedTransfer and added 3 blocks with components to it

**Comment by sschiessl-bcp** [comment]
Estimate 10 with implementation.
