### ISSUE TITLE
Show reason why a proposal has failed to execute

### ISSUE THREAD

**Issue by sschiessl-bcp** [blockchainprojects/bitshares-ui#61]
Original issue #2288

The failure reason should be one of the fields of the proposal object. Please suggest where to include the failure reason in the UI before implementation

**Comment by sschiessl-bcp** [comment]
Estimate: 4

**Comment by VerevkinAlexander** [comment]
Hi, @sschiessl-bcp.  I don't properly understand, how to reproduce the problem from task context. Can you give me a tip? 
http://joxi.ru/KAxxBZ5cMPKdMA

**Comment by sschiessl-bcp** [comment]
Have a look at components/Account/Proposal, in the render method
![image](https://user-images.githubusercontent.com/33128181/52329052-f96c6b00-29f1-11e9-89db-82396a32498e.png)

The proposal object should have a `fail_reason` field, if that is filled please show it in the UI. 

To create a failed proposal: Create a proposal for your own account and try to transfer more BTS than you currently have. Then approve the proposal, and the fail_reason should be filled.

**Comment by VerevkinAlexander** [comment]
> 
> 
> Have a look at components/Account/Proposal, in the render method
> ![image](https://user-images.githubusercontent.com/33128181/52329052-f96c6b00-29f1-11e9-89db-82396a32498e.png)
> 
> The proposal object should have a `fail_reason` field, if that is filled please show it in the UI.
> 
> To create a failed proposal: Create a proposal for your own account and try to transfer more BTS than you currently have. Then approve the proposal, and the fail_reason should be filled.
@sschiessl-bcp 
I have created a failed proposal in this way:

- send from one account to another more assets than it has
- to make this possible, I had to disable amount validation http://joxi.ru/D2PJzaBtpOeL9r in components/modal/SendModal
- than click on "approve" http://joxi.ru/l2Zb47VUwJ5J02, and approve transaction

After this in proposals obj, I could not find failed reason http://joxi.ru/82Q0BR7tjnMeym

**Comment by sschiessl-bcp** [comment]
What you have marked there are the proposal ids, you need the proposal object!

It should be available in the object stored in `proposal.proposal` that you can see in the screen you have posted above.

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp 
I checked "proposal.proposal" object, but `fail_reason` property is absent. Can be a problem in testnet? For checking on mainnet, I don't have account with assets.
http://joxi.ru/p27KalLCoaw3J2

**Comment by sschiessl-bcp** [comment]
I'm investigating, pause for now

**Comment by VerevkinAlexander** [comment]
During testing of creation of withdrawal permission, I have created proposal with invalid start date.
![image](https://user-images.githubusercontent.com/43240282/55156849-a8603400-5163-11e9-838c-68416ff95b94.png)
But, fail_reason property is absent.
