### ISSUE TITLE
[4] Add memo to every selector in the Barter proposal feature

### ISSUE THREAD

**Issue by sschiessl-bcp** [blockchainprojects/bitshares-ui#69]
Original Issue https://github.com/bitshares/bitshares-ui/issues/2408

Please checkout the changes I made to finalize the Barter feature. Next step now is to include an optional memo everywhere an amount is given.

![image](https://user-images.githubusercontent.com/33128181/51536703-c308ea80-1e4c-11e9-9617-430a34ea7886.png)

In the image that would be four places. I imagine to have an icon either on the left or right side of the amount selector, if the user pushes it, it adds a memo textfield under the amount. This must also be accounted for in the fee. For the encryption, the proposer will encrypt it for every respective receiver

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp after adding memos to elements of transfer list, I get error: http://joxi.ru/BA0j5y4HJ6z5gm
This is also true for "send" and "propose" transactions http://joxi.ru/ZrJJz6qt9Kgabr.
I think this issue is added in "2.0.19" version. Should I fix it?

**Comment by sschiessl-bcp** [comment]
Ah. I know what's broken. I ll fix that tomorrow.

**Comment by sschiessl-bcp** [comment]
How did you solve UX now?

**Comment by VerevkinAlexander** [comment]
It's ok, I will create a pull request today.

**Comment by sschiessl-bcp** [comment]
> It's ok, I will create a pull request today.

I see that the error http://joxi.net/BA0j5y4HJ6z5gm remains, I will have a look at that now

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp, I added _updateFee onMemoChanged.
