### ISSUE TITLE
"Send" transaction is failed

### ISSUE THREAD

**Issue by VerevkinAlexander** [blockchainprojects/bitshares-ui#72]
**Describe the bug**
Send transaction is failed.

**To Reproduce**
1. Go to https://develop.bitshares.org
2. Open menu.
3. Go to send or lagacy send.
4. Create a send transaction.
5. See error in console.

**Screenshots**
http://joxi.ru/VrwXEKQTOy3KEm

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome last
- version "2.0.190123-rc1"

**Comment by sschiessl-bcp** [comment]
Should work now, please confirm

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp 
I'm not sure. Now from "send" tab it creates a "send" proposal. But should perform direct send. Am I correct?
http://joxi.ru/Drl6gwOUvNDnW2

**Comment by sschiessl-bcp** [comment]
Apologies, I think our repository was not in-sync with bitshares.. 

It is now. Please rebase

**Comment by VerevkinAlexander** [comment]
Yes, now it's ok.
