### ISSUE TITLE
Can't switch to market trades when there isn't any history trades

### ISSUE THREAD

**Issue by sschiessl-bcp** [blockchainprojects/bitshares-ui#80]
https://github.com/bitshares/bitshares-ui/issues/2385

Please try to reproduce

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp 
I could not reproduce the issue.

Opened https://wallet.bitshares.org/#/market/CRYPTRADE.CRCO_CRYPTRADE.BTC link. Switched to "market trades" tab, http://joxi.ru/MAjQEvMf4M7qP2

Environment:
OS: macOS 10.14.3 and Win 10
Chorme and Mozilla latest
