### ISSUE TITLE
#2480

### ISSUE THREAD

**Issue by sschiessl-bcp** [blockchainprojects/bitshares-ui#82]
https://github.com/bitshares/bitshares-ui/issues/2480

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp 
So far, I have been unable to reproduce this issue, tried on different builds, mainnet and tesnet.

**Comment by sschiessl-bcp** [comment]
Are you running a dev setup? What is your console output when the asset select is visible? Got a screen?

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp 
I have tried on dev and prod versions. The console is clear http://joxi.ru/Rmz1ERgS08Q54r

**Comment by sschiessl-bcp** [comment]
Ok thank you!
