### ISSUE TITLE
[25] Implement recurring payment / direct debit mandate

### ISSUE THREAD

**Issue by driverdevteam** [blockchainprojects/bitshares-ui#84]
Implement the next spotlight: recurring payment / direct debit mandate

It will be a new panel that shows when you click on the spotlight with two sections. Within that panel, you will open one modal that is very similar to the send modal

> Also, You could go ahead and implement the basic structure required for that if you are idle otherwise

Context 1 - https://github.com/bitshares/bitshares-ui/issues/30#issuecomment-445986847 
Context 2 - https://github.com/bitshares/bitshares-ui/issues/2457#issue-410212107 
Context 3 - https://github.com/cryptonomex/graphene-ui/issues/639
Context 4 - https://github.com/bitshares/bitshares-ui/issues/1857

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp 
Could you shade some light about UX?
So after user clicks on "Direct debit" tab http://joxi.ru/p27KalLCoy5e62 it will see page (panel) with to sections, from there it can open modal, that contains this form http://joxi.ru/YmEJz4kt0N3N42

**Comment by sschiessl-bcp** [comment]
Who are you @driverdevteam ?

**Comment by sschiessl-bcp** [comment]
> @sschiessl-bcp
> Could you shade some light about UX?
> So after user clicks on "Direct debit" tab http://joxi.ru/p27KalLCoy5e62 it will see page (panel) with to sections, from there it can open modal, that contains this form http://joxi.ru/YmEJz4kt0N3N42

Yes exactly. I imagine the two sections to be on top of each other. 

The top panel will be a table-like view of all given and received direct debit mandates, the lower component will be with some descriptive text and explanations.

The table-like view will have a plus button in the top that opens the modal that you have posted. The modal will need similar features to the send modal (calculation of fees, show current balance of chosen asset). 

Should I create a mockup for you, or do you have an idea to proceed?

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp 
Please, create a mockup.

**Comment by sschiessl-bcp** [comment]
In general there are two operations that the [user can broadcast](https://github.com/bitshares/bitshares-ui/issues/30#issuecomment-273884878):
 - withdraw_permission_create_operation
 - withdraw_permission_claim_operation
The `withdraw_permission` returned from `get_full_account` (I think that is the default for ChainStore) contains information on all given and reveived withdrawal permissions.

<h2>Table</h2>
Put it in a Card, use the style guide table, for example like witness overview
![image](https://user-images.githubusercontent.com/33128181/53632510-7bc50500-3c15-11e9-8e97-4d0fb167bb4d.png)

<h4>Table Header</h4>
 - Filter component
 - Right next to it a button: "Create new mandate". 

<h4>Table Rows</h4>
 - id: id of the withdraw permission
 - type: string "receiver" or "giver" depending on the withdraw permission
 - authorized: if receiver, then the account that you are allowed to take out funds, if giver, then the account that is allowed to take funds from you
 - limit: how much can you still take in this period
 - until: the datetime when the current period ends
 - available: the currently available balance form the account that gives funds
 - action: if receiver, a button called "Collect", otherwise a button "Cancel"

<h4>Button "Create new mandate"</h4>
The button opens the modal shown here http://joxi.net/YmEJz4kt0N3N42

<h4>Button "Collect"</h4>
The button opens a similar one to the one shown here http://joxi.net/YmEJz4kt0N3N42. The modal has 
 - Authorizing account (looks the same as Authorized account, but not editable)
 - Withdrawal limit per period (looks the same, but not editable)
 - Amount field with asset and available balance (just like on Send Modal)

<h4>Button "Cancel"</h4>
Will broadcast an operation that cancels the permission, no model necessary

Skip a potential second card at the moment.

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp 
Is there a typo in mock-up http://joxi.ru/bmoLEDOUxp0yK2?
Should I make actual transaction to blockchain for "withdraw_permission_create_operation" and "withdraw_permission_claim_operation"? If so, is there a documentation about it's params?
And are there plans to add antd DatePicker component to bitshares-ui-style-guide? For now I'll customize antd DatePicker...

**Comment by sschiessl-bcp** [comment]
> @sschiessl-bcp
> Is there a typo in mock-up http://joxi.ru/bmoLEDOUxp0yK2?
> Should I make actual transaction to blockchain for "withdraw_permission_create_operation" and "withdraw_permission_claim_operation"? If so, is there a documentation about it's params?
> And are there plans to add antd DatePicker component to bitshares-ui-style-guide? For now I'll customize antd DatePicker...

- https://github.com/bitshares/bitshares-ui/issues/30#issuecomment-273884878
- We can move over the DatePicker to style guide when you are done

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp 
Could you tell me, what 25 and 27 number mean? http://joxi.ru/52abgGQU4VQPxA
And from your previous answer, I didn't understand next things. Should I make actual transaction to blockchain, or to stop on forming params for transaction in onSubmit method as in "Barter"?

**Comment by sschiessl-bcp** [comment]
Apologies for the lack of explanation.25 and 27 are the operation ids, and what you see there is the actual payload how it gets sent to the blockchain. The second argument is the payload, which corresponds to the arguments in bitsharesjs.

The ids are mapped to the operation name, to use them you do 
```
tr.add_type_operation("withdraw_permission_create", { // tr TransactionBuilder object
    "fee": {
      "amount": 0,
      "asset_id": "1.3.0"
    },
    "withdraw_from_account": "1.2.0",
    "authorized_account": "1.2.0",
    "withdrawal_limit": {
      "amount": 0,
      "asset_id": "1.3.0"
    },
    "withdrawal_period_sec": 0,
    "periods_until_expiration": 0,
    "period_start_time": "1970-01-01T00:00:00"
  }
);
```

More details are also listed here https://github.com/bitshares/bitsharesjs/blob/d99517326be645ece00bb694cc4248a742e86aee/lib/serializer/src/operations.js#L750

Having written that I see that there is an update operation as well `withdraw_permission_update`. So the modal to create a withdraw permission should be flexible enough to allow the creation of a new one, and the adjustment of an existing one.

It would be fine to build the construct and I include the actual call at the end

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp 
I have created modal for creation of withdraw permission and started working on table view. But to proceed I need data from blockchain. What should I do? Wait for you to implement call to blockchain for "withdraw_permission_create_operation"?

**Comment by sschiessl-bcp** [comment]
I'm working on implementing that on the background, please assume that there is a call that gives you withdrawal permissions for a given account id, and use a mockup object for now, e.g. 
```
withdraw_permission = {
    withdraw_from_account: "1.2.1235",
    "authorized_account": "1.2.1231",
    "withdrawal_limit": {
      "amount": 100,
      "asset_id": "1.3.0"
    },
    "withdrawal_period_sec": 60,
    "periods_until_expiration": 20,
    "period_start_time": "2019-03-15T08:00:00"
};
```

**Comment by sschiessl-bcp** [comment]
I've updated your branch to allow the creation of permissions, and have already created two if you want an account to test with. I have also included fetching the permissions.

The account with two permissions (one receiver onre giver) is blockchainprojectsbv-test-2.

Please continue :)

**Comment by OnyxPay** [comment]
@sschiessl-bcp 
Super, thanks a lot. I'll do.

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp 
Super, thanks a lot. I'll do.

**Comment by sschiessl-bcp** [comment]
Current state for that account 

![image](https://user-images.githubusercontent.com/33128181/54432058-6b8a4b00-4728-11e9-96f4-f3bfd88b21bb.png)

![image](https://user-images.githubusercontent.com/33128181/54432110-8f4d9100-4728-11e9-9380-b6aa034ad935.png)

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp 
Could you give me a hint?
In ClaimModal "amount to withdraw" field, user cant input more amount than maximum amount per period, correct? After user clicks on "AVAILABLE: 2,222.96895 TEST" this amount should not be added into "amount to withdraw" field ? 
![image](https://user-images.githubusercontent.com/43240282/54744879-c8767d00-4bd0-11e9-988c-502adfe09c02.png)

**Comment by sschiessl-bcp** [comment]
`Amount to Withdraw` should be tha maximum of `withdrawal_limit` and payer `account balance` of the same asset

**Comment by sschiessl-bcp** [comment]
I suppose having said that it makes sense to remove the "Maximum amount per period" and relabel the "Available:" to "Limit:".

If the available balance of the payer is less than the limit, add an icon "!" (exclamation-circle in antd) with a tooltip (I will fill in the text)

**Comment by sschiessl-bcp** [comment]
And instead of the "Maximum amount per period" field I think it would be nice to show the user instead there when the current period ends

**Comment by VerevkinAlexander** [comment]
Ok, I see.

What about fee calculation for create, update and claim. Should it be done like in "Send"? Only change operation type? In DirectDebit component you added estimateFeeAsync("proposal_create") as an example?
![image](https://user-images.githubusercontent.com/43240282/54746010-be09b280-4bd3-11e9-85fb-49663cbc46ab.png)

**Comment by sschiessl-bcp** [comment]
No, that must be from your intiial copy&paste.

Yes, fee calculation with adjusted operation type

**Comment by sschiessl-bcp** [comment]
@VerevkinAlexander 

Pull request towards bitshares is open: https://github.com/bitshares/bitshares-ui/pull/2554

Please check the source. 

1. I have added two `// todo:` tags to visualize possible error messages. You can add the next next to the create button
![image](https://user-images.githubusercontent.com/33128181/55084836-e39c2d80-50a5-11e9-8e02-56b761d4ed91.png)

2. Please put all not translated strings in the locale

3. Check the flow one time (create, update and claim, and cancel)

4. In `ApplicationApi.claimWithdrawPermission` the memo is currently not used. Please implement analogously to `transfer`

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp, ok I'll do it tomorrow morning.

**Comment by VerevkinAlexander** [comment]
>     1. I have added two `// todo:` tags to visualize possible error messages. You can add the next next to the create button

What type of errors are possible? For example when I create permission with start date from past, I get error in transaction popup.
![image](https://user-images.githubusercontent.com/43240282/55159219-3985d980-5169-11e9-8c74-77f70d726bde.png)

When I try to delete already deleted permission, I get:
![image](https://user-images.githubusercontent.com/43240282/55159073-fd527900-5168-11e9-9de8-3500b46f76f8.png)

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp 
When I update permission I should select new start date?
When I have left start date unchanged I've got the error:
![image](https://user-images.githubusercontent.com/43240282/55160623-6ab3d900-516c-11e9-9015-7d9112a02c0e.png)

**Comment by VerevkinAlexander** [comment]
Ok, I think, I've got your point. 
For example, something went wrong in `ApplicationApi.claimWithdrawPermission`, and this case we do not handling. In Claim modal's catch block we get a general error:
![image](https://user-images.githubusercontent.com/43240282/55216712-24ab5380-5206-11e9-8390-52b92f927553.png)

And errors in my examples above should be handled by form validation...
Am I right?

**Comment by VerevkinAlexander** [comment]
So far, I put all not translated strings in the locale. Checked the flow (create, update, claim, and cancel). In "ApplicationApi.claimWithdrawPermission" implemented the memo.
Fixed issues with the initial render of Table with permissions. Fixed "Current period ends" column of the table, for the case when the first period is not started. Removed "time now" button in antd DatePicker. Fixed validation of max limit in "Claim" modal.

**Comment by sschiessl-bcp** [comment]
I think all that is left now is `ApplicationApi.claimWithdrawPermission` error display, i added the error msg in the `DirectDebit` component.

Awesome you added the memo!

**Comment by sschiessl-bcp** [comment]
Finished it up!

**Comment by sschiessl-bcp** [comment]
Please re-iterate the changes I made to your code throughout the whole pull request, simply to have seen my intentions.
