### ISSUE TITLE
[4] #2499 Proposed Transactions

### ISSUE THREAD

**Issue by sschiessl-bcp** [blockchainprojects/bitshares-ui#85]
https://github.com/bitshares/bitshares-ui/issues/2499

**Comment by sschiessl-bcp** [comment]
In the dashboard of the UI there is a "Proposed Transaction" row. It renders a proposals and all contained operations.

This task is to render those operations in a more user friendly way.

First task for you: Get familiar how operations are rendered and ping me afterwards. I will then provide you what to show for each operation

**Comment by VerevkinAlexander** [comment]
I will take on this task after #84

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp 
Proposal operations are rendered by "ProposedOperation" component. It has switch-case conditions over operation type.
For example "transfer" operation: http://joxi.ru/BA0j5y4HJGoV9m we can see "TranslateWithLinks" component which renders text string http://joxi.ru/krDJzP9tEQ53P2

**Comment by sschiessl-bcp** [comment]
Ok super. 

In the first Step I would like you to refactor while keeping the existing logic. The goal is

 - each operation has its own component
 - the component lazy loads all information that it needs to render the operation. this can be either by receiving it via props, and if not given, fetches it by itself

**Comment by VerevkinAlexander** [comment]
> 
> 
> Ok super.
> 
> In the first Step I would like you to refactor while keeping the existing logic. The goal is
> 
>     * each operation has its own component
> 
>     * the component lazy loads all information that it needs to render the operation. this can be either by receiving it via props, and if not given, fetches it by itself


@sschiessl-bcp 
I have finished refactoring operations to separate react components. In total there are 51 operations.

**Comment by sschiessl-bcp** [comment]
Super!

Follow up with
 - reducing the massive switch `switch (ops[op[0]])` to fill the variable `column` into something like
```
import opComponents from "./operations";
column = opComponents.get(ops[op[0]], this.props, this.changeColor);
```
- checking how normal operations are rendered. Your changes are targeting the rendering of operations within a proposal. The operations are also rendered in the Account activity, how is it there?

**Comment by VerevkinAlexander** [comment]
>     * checking how normal operations are rendered. Your changes are targeting the rendering of operations within a proposal. The operations are also rendered in the Account activity, how is it there?

Inside the Activity tab, "RecentTransactions" component uses "Operation" component to render operations in a table like view.
This "Operation" component is very similar to "ProposedOperation" it also has a massive switch.
![image](https://user-images.githubusercontent.com/43240282/54671106-e0c99780-4afd-11e9-901e-d005d324f1a0.png)

For example, "proposal_create" operation in "Operation" component is uses "ProposedOperation" component.
![image](https://user-images.githubusercontent.com/43240282/54672056-e9bb6880-4aff-11e9-967a-55304a5a94ba.png)
![image](https://user-images.githubusercontent.com/43240282/54672158-2a1ae680-4b00-11e9-8a26-47b7a07c0db1.png)


In addition to "RecentTransactions" component, "Operation" component is also used inside: "TransactionConfirm", "Blocks", "Notifier".

**Comment by sschiessl-bcp** [comment]
Please refactor that as well to use the new components for each operation. If they are displayed differently, you could add a switch to it like 
```
column = opComponents.get(ops[op[0]], this.props, this.changeColor, flag);
```
where `flag` could be a string, e.g. `proposal`, `recent` or similar

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp 
I have finished refactoring of operations.

**Comment by sschiessl-bcp** [comment]
> @sschiessl-bcp
> I have finished refactoring of operations.

See comment on PR
