### ISSUE TITLE
[7] #1669

### ISSUE THREAD

**Issue by sschiessl-bcp** [blockchainprojects/bitshares-ui#86]
https://github.com/bitshares/bitshares-ui/issues/1669

Preliminary questions, when you have tradingview visible on an exchange: 
 - can you login there with a tradingview account to see your settings?
 - does it remember your drawings even without being logged in or saving a template?

If you save a template it should obviously be available on the site when loaded next time

**Comment by VerevkinAlexander** [comment]
> 
> 
> [bitshares#1669](https://github.com/bitshares/bitshares-ui/issues/1669)
> 
> Preliminary questions, when you have tradingview visible on an exchange:
> 
>     * can you login there with a tradingview account to see your settings?
> 
>     * does it remember your drawings even without being logged in or saving a template?
> 
> 
> If you save a template it should obviously be available on the site when loaded next time


Yes, I can log in to trading view (https://www.tradingview.com) or https://www.bitfinex.com/trading and see my settings, they are stored on a server.

Saving is available through different options: auto-save every 1 minute (optional), manual ... http://joxi.ru/eAOBzZ4Hx0qM62

Without being logged in it's not remembers my drawings.

**Comment by VerevkinAlexander** [comment]
On Bitshares trading view, I have found only option to save "indicator template" http://joxi.ru/J2bbg05UXjyWg2.
It works for indicators but not for drawings.

**Comment by sschiessl-bcp** [comment]
> > [bitshares#1669](https://github.com/bitshares/bitshares-ui/issues/1669)
> > Preliminary questions, when you have tradingview visible on an exchange:
> > ```
> > * can you login there with a tradingview account to see your settings?
> > 
> > * does it remember your drawings even without being logged in or saving a template?
> > ```
> > If you save a template it should obviously be available on the site when loaded next time
> 
> Yes, I can log in to trading view (https://www.tradingview.com) or https://www.bitfinex.com/trading and see my settings, they are stored on a server.
> 
> Saving is available through different options: auto-save every 1 minute (optional), manual ... http://joxi.ru/eAOBzZ4Hx0qM62
> 
> Without being logged in it's not remembers my drawings.

Ok, do you have an idea what we need to enable logging in on our site?

**Comment by sschiessl-bcp** [comment]
> On Bitshares trading view, I have found only option to save "indicator template" http://joxi.ru/J2bbg05UXjyWg2.
> It works for indicators but not for drawings.

Does this work without logging it?

**Comment by VerevkinAlexander** [comment]
Yes, these "study templates" are stored on tradingView servers. So when you save one, it's available everywhere.
![image](https://user-images.githubusercontent.com/43240282/54430005-d8064980-472a-11e9-8185-9493e80f8d53.png)
![image](https://user-images.githubusercontent.com/43240282/54430081-16036d80-472b-11e9-8f46-7f74305451bb.png)

**Comment by VerevkinAlexander** [comment]
> 
> 
> > > [bitshares#1669](https://github.com/bitshares/bitshares-ui/issues/1669)
> > > Preliminary questions, when you have tradingview visible on an exchange:
> > > ```
> > > * can you login there with a tradingview account to see your settings?
> > > 
> > > * does it remember your drawings even without being logged in or saving a template?
> > > ```
> > > If you save a template it should obviously be available on the site when loaded next time
> > 
> > 
> > Yes, I can log in to trading view (https://www.tradingview.com) or https://www.bitfinex.com/trading and see my settings, they are stored on a server.
> > Saving is available through different options: auto-save every 1 minute (optional), manual ... http://joxi.ru/eAOBzZ4Hx0qM62
> > Without being logged in it's not remembers my drawings.
> 
> Ok, do you have an idea what we need to enable logging in on our site?

Do you mean, logging in via account from https://www.tradingview.com ?
I think you didn't get my point: https://www.tradingview.com and https://www.bitfinex.com/trading implement separate log in logic, you can't login on https://www.bitfinex.com/trading with account from https://www.tradingview.com.

I guess, this https://www.jianshu.com/p/c2e9866c2b99 should be done to implement custom saving and loading of charts:

**Comment by sschiessl-bcp** [comment]
Ok I see. 

So I guess what I want is the login functionality that TradingView offers
![image](https://user-images.githubusercontent.com/33128181/54600322-ca0f3c00-4a3c-11e9-8881-0ee9b42044c1.png)

When I click Save there, it asks for a login
![image](https://user-images.githubusercontent.com/33128181/54600348-db584880-4a3c-11e9-8786-ca9c027e5203.png)

Please find out if that is TradingView default, or if that is proprietary and what login types we can support. Lowest level could be to put the config in localStorage

**Comment by VerevkinAlexander** [comment]
> 
> 
> Ok I see.
> 
> So I guess what I want is the login functionality that TradingView offers
> ![image](https://user-images.githubusercontent.com/33128181/54600322-ca0f3c00-4a3c-11e9-8881-0ee9b42044c1.png)
> 
> When I click Save there, it asks for a login
> ![image](https://user-images.githubusercontent.com/33128181/54600348-db584880-4a3c-11e9-8786-ca9c027e5203.png)
> 
> Please find out if that is TradingView default, or if that is proprietary and what login types we can support. Lowest level could be to put the config in localStorage

So in our case, we can save settings only local in localStorage, is it?

**Comment by sschiessl-bcp** [comment]
Yes, at the very least. Does TradingView come with any other default login choices?

**Comment by VerevkinAlexander** [comment]
I'll find out.

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp we can remove header_saveload feature from disabled_features and added it to enanabled_features https://github.com/blockchainprojects/bitshares-ui/blob/develop/app/components/Exchange/TradingViewPriceChart.jsx#L34 it gives us a chance to save chart

**Comment by sschiessl-bcp** [comment]
Yes, please try.

**Comment by VerevkinAlexander** [comment]
I `ve implemented it, please check
